services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - database
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./ml_worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - database
    deploy:
      replicas: 2
    restart: on-failure

  bot:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: ["python", "bot.py"]
    depends_on:
      - app
    restart: on-failure

  web-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: on-failure

  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    entrypoint: >
      sh -c '
        echo "Проверка наличия gemma3:4b"
        if curl -s http://ollama:11434/api/tags | grep -q "gemma3:4b"; then
          echo "gemma3:4b уже загружена"
        else
          echo "Загрузка gemma3:4b..."
          curl -X POST http://ollama:11434/api/pull \
            -d "{\"name\": \"gemma3:4b\"}" \
            --no-buffer
          echo ""
          echo "gemma3:4b загружена"
        fi
      '
    restart: "no"

volumes:
  rabbitmq_data:
  postgres_data:
  ollama_data:
